/** @type {import('../types.js').ProductDefinition} */
export const logYourBody = {
  schemaVersion: 1,
  id: 'logyourbody',
  identity: {
    name: 'LogYourBody',
    shortName: 'LYB',
    legalName: 'LogYourBody, Inc.',
    domain: 'logyourbody.com',
    bundleId: 'com.logyourbody.app',
    appStoreId: '6755209876',
  },
  brand: {
    promise: 'Answer “How am I doing?” with one private body-composition timeline.',
    slogan: 'Know if the work is working.',
    description:
      'Weight, body fat, lean mass, HealthKit, and progress photos in one private timeline.',
    voice: ['clear', 'concise', 'evidence-based', 'non-judgmental', 'private'],
    colors: { background: '#08090A', foreground: '#F7F8F8', accent: '#5E6AD2' },
    logos: {
      appIcon: '/brand/logyourbody-app-icon.png',
      wordmark: null,
      mark: null,
    },
  },
  links: {
    home: 'https://logyourbody.com',
    appStore: 'https://apps.apple.com/us/app/logyourbody/id6755209876',
    github: 'https://github.com/JovieInc/LogYourBody',
    privacy: 'https://logyourbody.com/privacy',
    terms: 'https://logyourbody.com/terms',
    support: 'https://logyourbody.com/support',
    status: 'https://status.logyourbody.com',
  },
  contacts: {
    support: 'support@logyourbody.com',
    privacy: 'privacy@logyourbody.com',
    legal: 'legal@logyourbody.com',
    careers: 'careers@logyourbody.com',
  },
  support: [
    {
      id: 'email',
      kind: 'email',
      label: 'Email support',
      description: 'Get help with your account, subscription, data, or the app.',
      href: 'mailto:support@logyourbody.com',
      responseTime: 'Usually within one business day',
      public: true,
    },
    {
      id: 'data-export',
      kind: 'self-service',
      label: 'Request a data export by email',
      description: 'Export from Settings, or ask support if you cannot access the app.',
      href: 'mailto:support@logyourbody.com?subject=LogYourBody%20Data%20Export%20Request',
      public: true,
    },
    {
      id: 'account-deletion',
      kind: 'self-service',
      label: 'Delete your account',
      description: 'Delete your account in the iOS app or use the support fallback.',
      href: '/delete-account',
      public: true,
    },
    {
      id: 'status',
      kind: 'status',
      label: 'System status',
      description: 'Check current service availability.',
      href: 'https://status.logyourbody.com',
      public: true,
    },
  ],
  messages: {
    landing: {
      headline: 'Know if the work is working.',
      subheading:
        'Weight, body fat, lean mass, and progress photos in one private timeline that shows the trend.',
      framingLine: 'One timeline. The signal, without the noise.',
      primaryCta: 'Download on the App Store',
    },
    waitlist: {
      success: "You're on the list. We'll email you when a TestFlight spot opens.",
      duplicate: "You're on the list. We'll email you when a TestFlight spot opens.",
      error: 'Something went wrong. Please try again.',
      invalidEmail: 'Enter a valid email address.',
    },
    paywall: {
      title: 'LogYourBody Pro',
      subtitle: 'A clear, private view of your progress.',
      valueProposition: 'Log quickly. See weight, body fat, FFMI, and your trend in one place.',
    },
  },
  features: [
    {
      id: 'body-metrics',
      name: 'Body metrics',
      description: 'Log weight, body fat, lean mass, and derived composition metrics.',
      category: 'measure',
      availability: 'available',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: true,
    },
    {
      id: 'healthkit-sync',
      name: 'HealthKit sync',
      description: 'Bring supported weight and activity data into the timeline.',
      category: 'import',
      availability: 'available',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: true,
    },
    {
      id: 'progress-photos',
      name: 'Progress photos',
      description: 'Keep private photos aligned with measurements over time.',
      category: 'measure',
      availability: 'available',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: true,
    },
    {
      id: 'private-timeline',
      name: 'Private timeline',
      description: 'See measurements and photos together without social comparison.',
      category: 'understand',
      availability: 'available',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: true,
    },
    {
      id: 'phase-insight',
      name: 'Phase insight',
      description: 'Classify supported trends as cutting, maintaining, or gaining.',
      category: 'understand',
      availability: 'beta',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: false,
    },
    {
      id: 'data-export',
      name: 'Data export',
      description: 'Take a portable copy of account and measurement data.',
      category: 'privacy',
      availability: 'available',
      platforms: ['ios', 'web'],
      entitlement: 'account',
      marketing: false,
    },
  ],
  plans: [
    {
      id: 'pro',
      name: 'Pro',
      tagline: 'The complete private body-composition timeline.',
      entitlement: 'Premium',
      featureIds: [
        'body-metrics',
        'healthkit-sync',
        'progress-photos',
        'private-timeline',
        'phase-insight',
        'data-export',
      ],
      trialDays: 3,
      pricing: {
        currency: 'USD',
        source: 'app-store-connect',
        monthly: {
          amount: 9.99,
          productId: 'com.logyourbody.app.pro1.monthly.3daytrial',
          packageId: '$rc_monthly',
        },
        annual: {
          amount: 69.99,
          productId: 'com.logyourbody.app.pro1.annual.3daytrial',
          packageId: '$rc_annual',
        },
      },
    },
  ],
  surfaces: [
    {
      id: 'ios-app',
      label: 'iOS app',
      route: 'logyourbody://',
      platform: 'ios',
      status: 'canonical',
      purpose: 'Paid product and complete body-composition loop.',
    },
    {
      id: 'marketing-home',
      label: 'Marketing home',
      route: '/',
      platform: 'web',
      status: 'supporting',
      purpose: 'Explain the product and route people to iOS.',
    },
    {
      id: 'support',
      label: 'Support',
      route: '/support',
      platform: 'web',
      status: 'supporting',
      purpose: 'Public help, account, data, and subscription recovery.',
    },
    {
      id: 'docs',
      label: 'Product docs',
      route: '/docs',
      platform: 'docs',
      status: 'deferred',
      purpose: 'Shared docs-shell destination; generated repository docs are canonical today.',
    },
    {
      id: 'web-dashboard',
      label: 'Web dashboard',
      route: '/dashboard',
      platform: 'web',
      status: 'deferred',
      purpose: 'Not a default product surface until the activation threshold is met.',
    },
  ],
  landingPages: [
    {
      id: 'app-store',
      route: '/',
      audience: 'adults tracking body composition',
      goal: 'download',
      sectionOrder: ['hero', 'product-proof', 'features', 'pricing', 'footer'],
      status: 'canonical',
    },
    {
      id: 'waitlist-editorial',
      route: '/',
      audience: 'pre-launch prospects',
      goal: 'waitlist',
      sectionOrder: ['hero', 'capture', 'product-proof', 'closing-line'],
      status: 'experiment',
    },
    {
      id: 'waitlist-minimal',
      route: '/',
      audience: 'pre-launch prospects',
      goal: 'waitlist',
      sectionOrder: ['brand', 'headline', 'capture'],
      status: 'rollback',
    },
  ],
};
