/** @type {import('../types.js').ProductDefinition} */
export const logYourBody = {
  schemaVersion: 1,
  id: 'logyourbody',
  identity: {
    name: 'LogYourBody',
    shortName: 'LYB',
    legalName: 'LogYourBody, Inc.',
    domain: 'logyourbody.com',
    bundleId: 'com.logyourbody.app',
    teamId: 'G24T327LXT',
    appStoreId: '6755209876',
  },
  brand: {
    promise: 'Answer “How am I doing?” with one private body-composition timeline.',
    slogan: 'Know if the work is working.',
    description:
      'Weight, body fat, lean mass, HealthKit data, and progress photos in one private timeline that shows the trend.',
    voice: ['clear', 'concise', 'evidence-based', 'non-judgmental', 'private'],
    colors: { background: '#08090A', foreground: '#F7F8F8', accent: '#5E6AD2' },
    logos: {
      appIcon: '/brand/logyourbody-app-icon.png',
      wordmark: null,
      mark: null,
    },
  },
  links: {
    home: 'https://logyourbody.com',
    appStore: 'https://apps.apple.com/us/app/logyourbody/id6755209876',
    github: 'https://github.com/JovieInc/LogYourBody',
    privacy: 'https://logyourbody.com/privacy',
    terms: 'https://logyourbody.com/terms',
    support: 'https://logyourbody.com/support',
    status: 'https://status.logyourbody.com',
  },
  endpoints: {
    hosts: {
      api: { host: 'www.logyourbody.com', url: 'https://www.logyourbody.com' },
      marketing: {
        host: 'logyourbody.com',
        url: 'https://logyourbody.com',
        note: 'Apex domain 307-redirects to www; never use it for API or auth traffic.',
      },
      status: { host: 'status.logyourbody.com', url: 'https://status.logyourbody.com' },
      dev: { host: 'localhost:3000', url: 'http://localhost:3000' },
    },
    auth: {
      issuer: 'https://jov.ie/api/auth',
      clients: {
        ios: {
          id: 'logyourbody-ios',
          redirectUri: 'logyourbody://oauth',
          scheme: 'logyourbody',
        },
        web: {
          id: 'logyourbody-web',
          redirectUri: 'https://www.logyourbody.com/api/auth/callback',
        },
      },
    },
    deepLinks: {
      applinksHosts: ['logyourbody.com', 'www.logyourbody.com'],
      scheme: 'logyourbody',
    },
    tables: [
      'profiles',
      'body_metrics',
      'daily_metrics',
      'app_users',
      'waitlist_entries',
      'progress_photos',
      'data_exports',
    ],
    buckets: ['photos'],
    vendor: {
      supabaseProjectRef: 'ihivupqpctpkrgqgxfjf',
      cloudinary: { apiHost: 'api.cloudinary.com', deliveryHost: 'res.cloudinary.com' },
      revenuecat: { apiHost: 'api.revenuecat.com' },
      statsig: { apiHost: 'statsigapi.net' },
      sentry: { ingestHost: '*.ingest.sentry.io' },
      bodyspec: { authHost: 'auth.bodyspec.com' },
      pravatar: { host: 'i.pravatar.cc' },
      github: {
        repo: 'https://github.com/JovieInc/LogYourBody',
        avatarsHost: 'avatars.githubusercontent.com',
      },
      apple: { appStore: 'https://apps.apple.com/us/app/logyourbody/id6755209876' },
    },
    allowlist: [
      { value: 'https://edpb.europa.eu', reason: 'Legal-doc link (EDPB) referenced by privacy copy.' },
      { value: 'https://apps.apple.com', reason: 'Apple storefront links.' },
      { value: 'https://appstoreconnect.apple.com', reason: 'App Store Connect links in release docs.' },
      { value: 'https://api.appstoreconnect.apple.com', reason: 'App Store Connect API base used by CI scripts.' },
      { value: 'https://testflight.apple.com', reason: 'TestFlight public links.' },
      { value: 'https://github.com/RevenueCat/purchases-ios', reason: 'SPM dependency repository.' },
      { value: 'https://github.com/getsentry/sentry-cocoa', reason: 'SPM dependency repository.' },
      { value: 'https://github.com/statsig-io/statsig-kit', reason: 'SPM dependency repository.' },
      { value: 'https://github.com/realm/SwiftLint', reason: 'SwiftLint build-tool repository.' },
      { value: 'https://github.com/JovieInc/certificates', reason: 'Fastlane Match certificates repository.' },
      { value: 'https://github.com/supabase/supabase-swift', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/clerk/clerk-ios', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/hmlongco/Factory', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/auth0/SimpleKeychain', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/kean/Get', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/vercel/next.js', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/facebook/react', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/microsoft/TypeScript', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/tailwindlabs/tailwindcss', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/radix-ui/primitives', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/lucide-icons/lucide', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/supabase/supabase-js', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/clerk/javascript', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/vercel/turbo', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/eslint/eslint', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://github.com/prettier/prettier', reason: 'OSS attribution in open-source-licenses.md.' },
      { value: 'https://schema.org', reason: 'JSON-LD structured-data vocabulary.' },
      { value: 'https://rubygems.org', reason: 'Ruby dependency host referenced by iOS tooling docs.' },
      { value: 'https://openapi.vercel.sh', reason: 'Vercel OpenAPI schema referenced by tooling.' },
      { value: 'https://deno.land', reason: 'Deno std module imports in Supabase edge functions.' },
      { value: 'https://esm.sh', reason: 'ESM CDN imports in Supabase edge functions.' },
      { value: 'https://api.cloudinary.com', reason: 'Cloudinary upload/delete API used by edge functions.' },
      { value: 'https://res.cloudinary.com', reason: 'Cloudinary delivery host for processed photos.' },
      { value: 'https://play.google.com', reason: 'Future Play Store listing link.' },
      { value: 'https://forms.gle', reason: 'Google Forms links in support docs.' },
      { value: 'https://twitter.com/itstimwhite', reason: 'Founder social link.' },
      { value: 'https://twitter.com/logyourbody', reason: 'Product social profile.' },
      { value: 'https://instagram.com/logyourbody', reason: 'Product social profile.' },
      { value: 'https://youtube.com/@logyourbody', reason: 'Product social profile.' },
      { value: 'https://api.github.com', reason: 'GitHub REST API used by CI scripts.' },
      { value: 'jov.ie', reason: 'First-party Jovie identity host (issuer contract is endpoints.auth).' },
      { value: 'https://github.com/JovieInc', reason: 'GitHub org page.' },
      { value: 'https://github.com/itstimwhite', reason: 'Pre-rename repo owner; URLs redirect to JovieInc.' },
      { value: 'https://github.com/yourusername/LogYourBody', reason: 'Clone placeholder in setup docs.' },
      { value: 'https://github.com/settings/tokens', reason: 'Token setup link in CI docs.' },
      { value: 'https://github.com/EmergeTools/ETTrace', reason: 'iOS performance tooling reference.' },
      { value: 'https://github.com/motdotla/dotenv', reason: 'Tooling reference in docs.' },
      { value: 'https://github.com/testing-library/jest-dom', reason: 'Testing library reference in docs.' },
      { value: 'https://github.com/johnno1962/injectionforxcode', reason: 'Xcode tooling reference in gitignore boilerplate.' },
      { value: 'https://github.com/', reason: 'CI scripts build repo URLs as https://github.com/${repository}.' },
      { value: 'https://cli.github.com', reason: 'GitHub CLI install link in docs.' },
      { value: 'https://developer.apple.com', reason: 'Apple developer documentation links.' },
      { value: 'https://help.apple.com', reason: 'Xcode-generated xcconfig help comment.' },
      {
        value: 'http://www.apple.com/DTDs/PropertyList-1.0.dtd',
        reason: 'Plist DTD namespace in Apple plist files.',
      },
      { value: 'https://app.revenuecat.com', reason: 'RevenueCat dashboard links.' },
      { value: 'https://www.revenuecat.com', reason: 'RevenueCat docs links.' },
      { value: 'https://docs.revenuecat.com', reason: 'RevenueCat docs links.' },
      { value: 'https://fastlane.tools', reason: 'Fastlane docs links.' },
      { value: 'https://docs.fastlane.tools', reason: 'Fastlane docs links.' },
      { value: 'https://guides.cocoapods.org', reason: 'CocoaPods guide link in gitignore boilerplate.' },
      { value: 'https://supabase.com', reason: 'Supabase docs and dashboard links.' },
      { value: 'https://cloudinary.com', reason: 'Cloudinary console link in edge-function docs.' },
      { value: 'https://openrouter.ai', reason: 'OpenRouter API used by advisory AI review CI.' },
      { value: 'https://platform.openai.com', reason: 'OpenAI platform link in CI docs.' },
      { value: 'https://claude.ai', reason: 'Claude product links in AI tooling docs.' },
      { value: 'https://registry.npmjs.org', reason: 'npm registry configured in .npmrc.' },
      { value: 'https://vercel.com', reason: 'Vercel dashboard links in deploy docs.' },
      { value: 'https://nextjs.org', reason: 'Next.js documentation links.' },
      { value: 'https://react.dev', reason: 'React documentation links.' },
      { value: 'https://www.typescriptlang.org', reason: 'TypeScript documentation links.' },
      { value: 'https://tailwindcss.com', reason: 'Tailwind documentation links.' },
      { value: 'https://vitest.dev', reason: 'Vitest documentation links.' },
      { value: 'https://playwright.dev', reason: 'Playwright documentation links.' },
      { value: 'https://turbo.build', reason: 'Turborepo schema/docs links.' },
      { value: 'https://web.dev', reason: 'web.dev PWA guide links.' },
      { value: 'https://developer.chrome.com', reason: 'Chrome developer documentation links.' },
      { value: 'https://semver.org', reason: 'Semver specification links.' },
      { value: 'https://keepachangelog.com', reason: 'Keep a Changelog format link.' },
      { value: 'https://www.w3.org', reason: 'W3C accessibility documentation links.' },
      { value: 'http://www.w3.org', reason: 'SVG XML namespace identifiers.' },
      { value: 'https://linkedin.com/in/timwhite', reason: 'Founder social link.' },
      { value: 'https://smpl-x.is.tue.mpg.de', reason: 'SMPL-X body-model reference in avatar docs.' },
      { value: 'https://e', reason: 'Compact fixture host in timeline scrub tests.' },
      {
        value: 'https://przjeunffnkjzxpykvjn.supabase.co',
        reason: 'Existing dev Supabase project ref; do not add new ones.',
      },
      {
        value: 'https://blhpuaqbbczzhsshumof.supabase.co',
        reason: 'Existing dev Supabase project ref; do not add new ones.',
      },
      {
        value: 'https://0fab5338-b5f2-48af-a596-591bb5b0a51c.supabase.co',
        reason: 'Existing dev Supabase project ref; do not add new ones.',
      },
      {
        value: 'https://170c7ac4-6923-4c10-b560-55d3f97e1370.supabase.co',
        reason: 'Existing dev Supabase project ref; do not add new ones.',
      },
      {
        value: 'https://378a4e19-4a7d-4c2d-9f54-a28537a0e1a8.supabase.co',
        reason: 'Existing dev Supabase project ref; do not add new ones.',
      },
    ],
  },
  contacts: {
    support: 'support@logyourbody.com',
    privacy: 'privacy@logyourbody.com',
    legal: 'legal@logyourbody.com',
    careers: 'careers@logyourbody.com',
  },
  support: [
    {
      id: 'email',
      kind: 'email',
      label: 'Email support',
      description: 'Get help with your account, subscription, data, or the app.',
      href: 'mailto:support@logyourbody.com',
      responseTime: 'Usually within one business day',
      public: true,
    },
    {
      id: 'data-export',
      kind: 'self-service',
      label: 'Request a data export by email',
      description: 'Export from Settings, or ask support if you cannot access the app.',
      href: 'mailto:support@logyourbody.com?subject=LogYourBody%20Data%20Export%20Request',
      public: true,
    },
    {
      id: 'account-deletion',
      kind: 'self-service',
      label: 'Delete your account',
      description: 'Delete your account in the iOS app or use the support fallback.',
      href: '/delete-account',
      public: true,
    },
    {
      id: 'status',
      kind: 'status',
      label: 'System status',
      description: 'Check current service availability.',
      href: 'https://status.logyourbody.com',
      public: true,
    },
  ],
  messages: {
    landing: {
      headline: 'Know if the work is working.',
      subheading:
        'Weight, body fat, lean mass, and progress photos in one private timeline that shows the trend.',
      framingLine: 'One timeline. The signal, without the noise.',
      primaryCta: 'Download on the App Store',
    },
    waitlist: {
      success: "You're on the list. We'll email you when a TestFlight spot opens.",
      duplicate: "You're on the list. We'll email you when a TestFlight spot opens.",
      error: 'Something went wrong. Please try again.',
      invalidEmail: 'Enter a valid email address.',
    },
    paywall: {
      title: 'LogYourBody Pro',
      subtitle: 'A clear, private view of your progress.',
      valueProposition: 'Log quickly. See weight, body fat, FFMI, and your trend in one place.',
    },
  },
  features: [
    {
      id: 'body-metrics',
      name: 'Body metrics',
      description: 'Log weight, body fat, lean mass, and derived composition metrics.',
      category: 'measure',
      availability: 'available',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: true,
    },
    {
      id: 'healthkit-sync',
      name: 'HealthKit sync',
      description: 'Bring supported weight and activity data into the timeline.',
      category: 'import',
      availability: 'available',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: true,
    },
    {
      id: 'progress-photos',
      name: 'Progress photos',
      description: 'Keep private photos aligned with measurements over time.',
      category: 'measure',
      availability: 'available',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: true,
    },
    {
      id: 'private-timeline',
      name: 'Private timeline',
      description: 'See measurements and photos together without social comparison.',
      category: 'understand',
      availability: 'available',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: true,
    },
    {
      id: 'phase-insight',
      name: 'Phase insight',
      description: 'Classify supported trends as cutting, maintaining, or gaining.',
      category: 'understand',
      availability: 'beta',
      platforms: ['ios'],
      entitlement: 'premium',
      marketing: false,
    },
    {
      id: 'data-export',
      name: 'Data export',
      description: 'Take a portable copy of account and measurement data.',
      category: 'privacy',
      availability: 'available',
      platforms: ['ios', 'web'],
      entitlement: 'account',
      marketing: false,
    },
  ],
  plans: [
    {
      id: 'pro',
      name: 'Pro',
      tagline: 'The complete private body-composition timeline.',
      entitlement: 'Premium',
      featureIds: [
        'body-metrics',
        'healthkit-sync',
        'progress-photos',
        'private-timeline',
        'phase-insight',
        'data-export',
      ],
      trialDays: 3,
      pricing: {
        currency: 'USD',
        source: 'app-store-connect',
        monthly: {
          amount: 9.99,
          productId: 'com.logyourbody.app.pro1.monthly.3daytrial',
          packageId: '$rc_monthly',
        },
        annual: {
          amount: 69.99,
          productId: 'com.logyourbody.app.pro1.annual.3daytrial',
          packageId: '$rc_annual',
        },
      },
    },
  ],
  surfaces: [
    {
      id: 'ios-app',
      label: 'iOS app',
      route: 'logyourbody://',
      platform: 'ios',
      status: 'canonical',
      purpose: 'Paid product and complete body-composition loop.',
    },
    {
      id: 'marketing-home',
      label: 'Marketing home',
      route: '/',
      platform: 'web',
      status: 'supporting',
      purpose: 'Explain the product and route people to iOS.',
    },
    {
      id: 'support',
      label: 'Support',
      route: '/support',
      platform: 'web',
      status: 'supporting',
      purpose: 'Public help, account, data, and subscription recovery.',
    },
    {
      id: 'docs',
      label: 'Product docs',
      route: '/docs',
      platform: 'docs',
      status: 'deferred',
      purpose: 'Shared docs-shell destination; generated repository docs are canonical today.',
    },
    {
      id: 'web-dashboard',
      label: 'Web dashboard',
      route: '/dashboard',
      platform: 'web',
      status: 'deferred',
      purpose: 'Not a default product surface until the activation threshold is met.',
    },
  ],
  landingPages: [
    {
      id: 'app-store',
      route: '/',
      audience: 'adults tracking body composition',
      goal: 'download',
      sectionOrder: ['hero', 'product-proof', 'features', 'pricing', 'footer'],
      status: 'canonical',
    },
    {
      id: 'waitlist-editorial',
      route: '/',
      audience: 'pre-launch prospects',
      goal: 'waitlist',
      sectionOrder: ['hero', 'capture', 'product-proof', 'closing-line'],
      status: 'experiment',
    },
    {
      id: 'waitlist-minimal',
      route: '/',
      audience: 'pre-launch prospects',
      goal: 'waitlist',
      sectionOrder: ['brand', 'headline', 'capture'],
      status: 'rollback',
    },
  ],
};
