#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="${IOS_CONFIG_OUTPUT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
CONFIG_DIR="$IOS_DIR/LogYourBody"
CONFIG_FILE="$CONFIG_DIR/Config.xcconfig"

lowercase() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

is_placeholder() {
  local value
  value="$(lowercase "$1")"

  case "$value" in
    ""|*"\$("*|*your-*|*placeholder*|*replace*|*todo*|*changeme*|*xxx*|*"*"*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

fail() {
  echo "::error::$1" >&2
  exit 1
}

require_value() {
  local name="$1"
  local value="$2"

  if is_placeholder "$value"; then
    fail "$name must be set to a real production value before building iOS release artifacts."
  fi
}

require_https_url() {
  local name="$1"
  local value="$2"

  if ! ruby -ruri -e 'uri = URI(ARGV.fetch(0)); exit(uri.is_a?(URI::HTTPS) && uri.host && !uri.host.empty? ? 0 : 1)' "$value"; then
    fail "$name must be a valid HTTPS URL."
  fi
}

require_probability() {
  local name="$1"
  local value="$2"

  if ! ruby -e 'value = Float(ARGV.fetch(0)); exit(value >= 0.0 && value <= 1.0 ? 0 : 1)' "$value"; then
    fail "$name must be a number between 0 and 1 for iOS production releases."
  fi
}

host_for_url() {
  ruby -ruri -e 'uri = URI(ARGV.fetch(0)); abort unless uri.host && !uri.host.empty?; print uri.host' "$1"
}

xcconfig_url() {
  printf '%s' "$1" | sed "s#://#:/\$()/#"
}

REVENUE_CAT_PUBLIC_KEY="${REVENUE_CAT_PUBLIC_KEY:-}"
AUTH_ISSUER="${AUTH_ISSUER:-https://jov.ie/api/auth}"
AUTH_CLIENT_ID="${AUTH_CLIENT_ID:-logyourbody-ios}"
AUTH_REDIRECT_URI="${AUTH_REDIRECT_URI:-logyourbody://oauth}"
API_BASE_URL="${API_BASE_URL:-https://www.logyourbody.com}"
STATSIG_CLIENT_SDK_KEY="${STATSIG_CLIENT_SDK_KEY:-}"
STATSIG_ENVIRONMENT_TIER="${STATSIG_ENVIRONMENT_TIER:-production}"
SENTRY_DSN="${SENTRY_DSN:-}"
SENTRY_ENVIRONMENT="${SENTRY_ENVIRONMENT:-production}"
SENTRY_TRACES_SAMPLE_RATE="${SENTRY_TRACES_SAMPLE_RATE:-0.1}"
BODYSPEC_CLIENT_ID="${BODYSPEC_CLIENT_ID:-}"
BODYSPEC_REDIRECT_URI="${BODYSPEC_REDIRECT_URI:-}"

require_value "REVENUE_CAT_PUBLIC_KEY" "$REVENUE_CAT_PUBLIC_KEY"
require_value "AUTH_ISSUER" "$AUTH_ISSUER"
require_value "AUTH_CLIENT_ID" "$AUTH_CLIENT_ID"
require_value "AUTH_REDIRECT_URI" "$AUTH_REDIRECT_URI"
require_value "API_BASE_URL" "$API_BASE_URL"

require_https_url "AUTH_ISSUER" "$AUTH_ISSUER"
require_https_url "API_BASE_URL" "$API_BASE_URL"

if [ "$AUTH_ISSUER" != "https://jov.ie/api/auth" ]; then
  fail "AUTH_ISSUER must be https://jov.ie/api/auth for iOS production releases."
fi

if [ "$AUTH_CLIENT_ID" != "logyourbody-ios" ]; then
  fail "AUTH_CLIENT_ID must be logyourbody-ios for iOS production releases."
fi

if [ "$AUTH_REDIRECT_URI" != "logyourbody://oauth" ]; then
  fail "AUTH_REDIRECT_URI must be logyourbody://oauth for iOS production releases."
fi

bash "$SCRIPT_DIR/verify_upload_hosts.sh"

case "$REVENUE_CAT_PUBLIC_KEY" in
  appl_*) ;;
  sk_*) fail "REVENUE_CAT_PUBLIC_KEY must be the iOS public SDK key, not a RevenueCat secret API key." ;;
  *) fail "REVENUE_CAT_PUBLIC_KEY must be a RevenueCat iOS public SDK key that starts with appl_." ;;
esac

if [ -n "$SENTRY_DSN" ]; then
  require_https_url "SENTRY_DSN" "$SENTRY_DSN"
fi

if [ "$STATSIG_ENVIRONMENT_TIER" != "production" ]; then
  fail "STATSIG_ENVIRONMENT_TIER must be production for iOS production releases."
fi

if [ "$SENTRY_ENVIRONMENT" != "production" ]; then
  fail "SENTRY_ENVIRONMENT must be production for iOS production releases."
fi

require_probability "SENTRY_TRACES_SAMPLE_RATE" "$SENTRY_TRACES_SAMPLE_RATE"

API_EXPECTED_HOST="${API_EXPECTED_HOST:-$(host_for_url "$API_BASE_URL")}"

if [ "$API_EXPECTED_HOST" != "$(host_for_url "$API_BASE_URL")" ]; then
  fail "API_EXPECTED_HOST must match API_BASE_URL host."
fi

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
// Generated by apps/ios/Scripts/write_release_config.sh. Do not commit.

APP_ENVIRONMENT = production
ALLOW_PRODUCTION_SERVICES_IN_DEBUG = NO

AUTH_ISSUER = $(xcconfig_url "$AUTH_ISSUER")
AUTH_CLIENT_ID = $AUTH_CLIENT_ID
AUTH_REDIRECT_URI = $(xcconfig_url "$AUTH_REDIRECT_URI")

API_BASE_URL = $(xcconfig_url "$API_BASE_URL")
API_EXPECTED_HOST = $API_EXPECTED_HOST

REVENUE_CAT_API_KEY = $REVENUE_CAT_PUBLIC_KEY
STATSIG_CLIENT_SDK_KEY = $STATSIG_CLIENT_SDK_KEY
STATSIG_ENVIRONMENT_TIER = production
SENTRY_DSN = $(xcconfig_url "$SENTRY_DSN")
SENTRY_ENVIRONMENT = production
SENTRY_TRACES_SAMPLE_RATE = $SENTRY_TRACES_SAMPLE_RATE

BODYSPEC_CLIENT_ID = $BODYSPEC_CLIENT_ID
BODYSPEC_REDIRECT_URI = $(xcconfig_url "$BODYSPEC_REDIRECT_URI")
EOF

{
  echo "## iOS Release Observability"
  echo ""
  if [ -n "$SENTRY_DSN" ]; then
    echo "- Sentry configured: true"
  else
    echo "- Sentry configured: false"
  fi
  if [ -n "$STATSIG_CLIENT_SDK_KEY" ]; then
    echo "- Statsig configured: true"
  else
    echo "- Statsig configured: false"
  fi
  echo "- Sentry traces sample rate valid: true"
  if [ -n "$SENTRY_DSN" ] || [ -n "$STATSIG_CLIENT_SDK_KEY" ]; then
    echo "- Provider smoke proof required: true"
  else
    echo "- Provider smoke proof required: false"
  fi
  echo "- Values redacted: true"
} | tee "$CONFIG_DIR/release-observability.md" >/dev/null

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  cat "$CONFIG_DIR/release-observability.md" >> "$GITHUB_STEP_SUMMARY"
fi

echo "Wrote production iOS release config files."
