#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="${IOS_CONFIG_OUTPUT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
CONFIG_DIR="$IOS_DIR/LogYourBody"
CONFIG_FILE="$CONFIG_DIR/Config.xcconfig"
SUPABASE_FILE="$IOS_DIR/Supabase.xcconfig"

lowercase() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

is_placeholder() {
  local value
  value="$(lowercase "$1")"

  case "$value" in
    ""|*"\$("*|*your-*|*placeholder*|*replace*|*todo*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

fail() {
  echo "::error::$1" >&2
  exit 1
}

require_value() {
  local name="$1"
  local value="$2"

  if is_placeholder "$value"; then
    fail "$name must be set to a real production value before building iOS release artifacts."
  fi
}

require_https_url() {
  local name="$1"
  local value="$2"

  if ! ruby -ruri -e 'uri = URI(ARGV.fetch(0)); exit(uri.is_a?(URI::HTTPS) && uri.host && !uri.host.empty? ? 0 : 1)' "$value"; then
    fail "$name must be a valid HTTPS URL."
  fi
}

host_for_url() {
  ruby -ruri -e 'uri = URI(ARGV.fetch(0)); abort unless uri.host && !uri.host.empty?; print uri.host' "$1"
}

xcconfig_url() {
  printf '%s' "$1" | sed "s#://#:/\$()/#"
}

CLERK_PUBLISHABLE_KEY="${CLERK_PUBLISHABLE_KEY:-${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}}"
SUPABASE_URL="${SUPABASE_URL:-${NEXT_PUBLIC_SUPABASE_URL:-}}"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-${NEXT_PUBLIC_SUPABASE_ANON_KEY:-${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY:-}}}"
REVENUE_CAT_PUBLIC_KEY="${REVENUE_CAT_PUBLIC_KEY:-}"
CLERK_FRONTEND_API="${CLERK_FRONTEND_API:-https://clerk.logyourbody.com}"
API_BASE_URL="${API_BASE_URL:-https://www.logyourbody.com}"
STATSIG_CLIENT_SDK_KEY="${STATSIG_CLIENT_SDK_KEY:-}"
STATSIG_ENVIRONMENT_TIER="${STATSIG_ENVIRONMENT_TIER:-production}"
SENTRY_DSN="${SENTRY_DSN:-}"
SENTRY_ENVIRONMENT="${SENTRY_ENVIRONMENT:-production}"
SENTRY_TRACES_SAMPLE_RATE="${SENTRY_TRACES_SAMPLE_RATE:-0.1}"
BODYSPEC_CLIENT_ID="${BODYSPEC_CLIENT_ID:-}"
BODYSPEC_REDIRECT_URI="${BODYSPEC_REDIRECT_URI:-}"

require_value "CLERK_PUBLISHABLE_KEY" "$CLERK_PUBLISHABLE_KEY"
require_value "SUPABASE_URL" "$SUPABASE_URL"
require_value "SUPABASE_ANON_KEY" "$SUPABASE_ANON_KEY"
require_value "REVENUE_CAT_PUBLIC_KEY" "$REVENUE_CAT_PUBLIC_KEY"
require_value "CLERK_FRONTEND_API" "$CLERK_FRONTEND_API"
require_value "API_BASE_URL" "$API_BASE_URL"

case "$CLERK_PUBLISHABLE_KEY" in
  pk_live_*) ;;
  *) fail "CLERK_PUBLISHABLE_KEY must be a Clerk live publishable key for iOS production releases." ;;
esac

require_https_url "SUPABASE_URL" "$SUPABASE_URL"
require_https_url "CLERK_FRONTEND_API" "$CLERK_FRONTEND_API"
require_https_url "API_BASE_URL" "$API_BASE_URL"

case "$REVENUE_CAT_PUBLIC_KEY" in
  appl_*) ;;
  sk_*) fail "REVENUE_CAT_PUBLIC_KEY must be the iOS public SDK key, not a RevenueCat secret API key." ;;
  *) fail "REVENUE_CAT_PUBLIC_KEY must be a RevenueCat iOS public SDK key that starts with appl_." ;;
esac

if [ -n "$SENTRY_DSN" ]; then
  require_https_url "SENTRY_DSN" "$SENTRY_DSN"
fi

if [ "$STATSIG_ENVIRONMENT_TIER" != "production" ]; then
  fail "STATSIG_ENVIRONMENT_TIER must be production for iOS production releases."
fi

if [ "$SENTRY_ENVIRONMENT" != "production" ]; then
  fail "SENTRY_ENVIRONMENT must be production for iOS production releases."
fi

SUPABASE_EXPECTED_HOST="${SUPABASE_EXPECTED_HOST:-$(host_for_url "$SUPABASE_URL")}"
API_EXPECTED_HOST="${API_EXPECTED_HOST:-$(host_for_url "$API_BASE_URL")}"

if [ "$SUPABASE_EXPECTED_HOST" != "$(host_for_url "$SUPABASE_URL")" ]; then
  fail "SUPABASE_EXPECTED_HOST must match SUPABASE_URL host."
fi

if [ "$API_EXPECTED_HOST" != "$(host_for_url "$API_BASE_URL")" ]; then
  fail "API_EXPECTED_HOST must match API_BASE_URL host."
fi

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
// Generated by apps/ios/Scripts/write_release_config.sh. Do not commit.

APP_ENVIRONMENT = production
ALLOW_PRODUCTION_SERVICES_IN_DEBUG = NO

CLERK_PUBLISHABLE_KEY = $CLERK_PUBLISHABLE_KEY
CLERK_FRONTEND_API = $(xcconfig_url "$CLERK_FRONTEND_API")

SUPABASE_URL = $(xcconfig_url "$SUPABASE_URL")
SUPABASE_EXPECTED_HOST = $SUPABASE_EXPECTED_HOST
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY

API_BASE_URL = $(xcconfig_url "$API_BASE_URL")
API_EXPECTED_HOST = $API_EXPECTED_HOST

REVENUE_CAT_API_KEY = $REVENUE_CAT_PUBLIC_KEY
STATSIG_CLIENT_SDK_KEY = $STATSIG_CLIENT_SDK_KEY
STATSIG_ENVIRONMENT_TIER = production
SENTRY_DSN = $(xcconfig_url "$SENTRY_DSN")
SENTRY_ENVIRONMENT = production
SENTRY_TRACES_SAMPLE_RATE = $SENTRY_TRACES_SAMPLE_RATE

BODYSPEC_CLIENT_ID = $BODYSPEC_CLIENT_ID
BODYSPEC_REDIRECT_URI = $(xcconfig_url "$BODYSPEC_REDIRECT_URI")
EOF

cat > "$SUPABASE_FILE" <<EOF
// Generated by apps/ios/Scripts/write_release_config.sh. Do not commit.
SUPABASE_URL = $(xcconfig_url "$SUPABASE_URL")
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
EOF

{
  echo "## iOS Release Observability"
  echo ""
  if [ -n "$SENTRY_DSN" ]; then
    echo "- Sentry configured: true"
  else
    echo "- Sentry configured: false"
  fi
  if [ -n "$STATSIG_CLIENT_SDK_KEY" ]; then
    echo "- Statsig configured: true"
  else
    echo "- Statsig configured: false"
  fi
  echo "- Values redacted: true"
} | tee "$CONFIG_DIR/release-observability.md" >/dev/null

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  cat "$CONFIG_DIR/release-observability.md" >> "$GITHUB_STEP_SUMMARY"
fi

echo "Wrote production iOS release config files."
