// Generated by packages/product-registry/scripts/generate.mjs. Do not edit.
import Foundation

enum ProductRegistry {
    static let appName = "LogYourBody"
    static let legalName = "LogYourBody, Inc."
    static let slogan = "Know if the work is working."
    static let productDescription =
        "Weight, body fat, lean mass, HealthKit data, and progress photos in one private timeline that shows the trend."
    static let supportEmail = "support@logyourbody.com"
    static let appStoreURL = "https://apps.apple.com/us/app/logyourbody/id6755209876"

    enum Contacts {
        static let support = "support@logyourbody.com"
        static let privacy = "privacy@logyourbody.com"
        static let legal = "legal@logyourbody.com"
        static let careers = "careers@logyourbody.com"
    }

    enum Paywall {
        static let title = "Keep the answer current."
        static let subtitle = "Your first score is ready. Pro keeps it updated as new measurements and photos arrive."
        static let valueProposition = "Track weight, body fat, FFMI, and honest visual change with one private history."
        static let entitlementID = "Premium"
        static let trialDays = 3
        static let monthlyProductID = "com.logyourbody.app.pro1.monthly.3daytrial"
        static let annualProductID = "com.logyourbody.app.pro1.annual.3daytrial"
        static let monthlyPackageID = "$rc_monthly"
        static let annualPackageID = "$rc_annual"
        static let monthlyReferencePrice = "9.99"
        static let annualReferencePrice = "69.99"
        static let monthlyReferenceLocalizedPrice = "$9.99"
        static let annualReferenceLocalizedPrice = "$69.99"
        static let featureNames = [
            "Body metrics",
            "HealthKit sync",
            "Progress photos",
            "Private timeline"
        ]
    }

    enum Hosts {
        static let api = "https://www.logyourbody.com"
        static let apiHost = "www.logyourbody.com"
        static let marketing = "https://logyourbody.com"
        static let status = "https://status.logyourbody.com"
    }

    enum Auth {
        static let issuer = "https://jov.ie/api/auth"
        static let iosClientID = "logyourbody-ios"
        static let iosRedirectURI = "logyourbody://oauth"
        static let callbackScheme = "logyourbody"
    }
}
