// Generated by packages/product-registry/scripts/generate.mjs. Do not edit.
import Foundation

enum ProductRegistry {
    static let appName = "LogYourBody"
    static let legalName = "LogYourBody, Inc."
    static let slogan = "Know if the work is working."
    static let productDescription =
        "Weight, body fat, lean mass, HealthKit data, and progress photos in one private timeline that shows the trend."
    static let supportEmail = "support@logyourbody.com"
    static let appStoreURL = "https://apps.apple.com/us/app/logyourbody/id6755209876"

    enum Contacts {
        static let support = "support@logyourbody.com"
        static let privacy = "privacy@logyourbody.com"
        static let legal = "legal@logyourbody.com"
        static let careers = "careers@logyourbody.com"
    }

    enum Paywall {
        static let title = "LogYourBody Pro"
        static let subtitle = "A clear, private view of your progress."
        static let valueProposition = "Log quickly. See weight, body fat, FFMI, and your trend in one place."
        static let entitlementID = "Premium"
        static let trialDays = 3
        static let monthlyProductID = "com.logyourbody.app.pro1.monthly.3daytrial"
        static let annualProductID = "com.logyourbody.app.pro1.annual.3daytrial"
        static let monthlyPackageID = "$rc_monthly"
        static let annualPackageID = "$rc_annual"
        static let monthlyReferencePrice = "9.99"
        static let annualReferencePrice = "69.99"
        static let monthlyReferenceLocalizedPrice = "$9.99"
        static let annualReferenceLocalizedPrice = "$69.99"
        static let featureNames = [
            "Body metrics",
            "HealthKit sync",
            "Progress photos",
            "Private timeline"
        ]
    }
}
