import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';
import { format, resolveConfig } from 'prettier';
import { logYourBody } from '../src/products/logyourbody.mjs';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(packageRoot, '../..');
const swiftPath = resolve(repoRoot, 'apps/ios/LogYourBody/GeneratedProductRegistry.swift');
const docsPath = resolve(repoRoot, 'docs/product/product-registry.generated.md');
const endpointsTsPath = resolve(repoRoot, 'apps/web/src/lib/generated/endpoints.generated.ts');
const cspTsPath = resolve(repoRoot, 'apps/web/src/lib/generated/csp.generated.ts');
const aasaWellKnownPath = resolve(
  repoRoot,
  'apps/web/public/.well-known/apple-app-site-association',
);
const aasaRootPath = resolve(repoRoot, 'apps/web/public/apple-app-site-association');
const check = process.argv.includes('--check');

const swiftString = (value) => `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
const plan = logYourBody.plans[0];
const marketingFeatures = logYourBody.features.filter((feature) => feature.marketing);
const { endpoints } = logYourBody;

const featureNames = marketingFeatures
  .map((feature) => swiftString(feature.name))
  .join(',\n            ');
const swift = `// Generated by packages/product-registry/scripts/generate.mjs. Do not edit.
import Foundation

enum ProductRegistry {
    static let appName = ${swiftString(logYourBody.identity.name)}
    static let legalName = ${swiftString(logYourBody.identity.legalName)}
    static let slogan = ${swiftString(logYourBody.brand.slogan)}
    static let productDescription =
        ${swiftString(logYourBody.brand.description)}
    static let supportEmail = ${swiftString(logYourBody.contacts.support)}
    static let appStoreURL = ${swiftString(logYourBody.links.appStore)}

    enum Contacts {
        static let support = ${swiftString(logYourBody.contacts.support)}
        static let privacy = ${swiftString(logYourBody.contacts.privacy)}
        static let legal = ${swiftString(logYourBody.contacts.legal)}
        static let careers = ${swiftString(logYourBody.contacts.careers)}
    }

    enum Paywall {
        static let title = ${swiftString(logYourBody.messages.paywall.title)}
        static let subtitle = ${swiftString(logYourBody.messages.paywall.subtitle)}
        static let valueProposition = ${swiftString(logYourBody.messages.paywall.valueProposition)}
        static let entitlementID = ${swiftString(plan.entitlement)}
        static let trialDays = ${plan.trialDays}
        static let monthlyProductID = ${swiftString(plan.pricing.monthly.productId)}
        static let annualProductID = ${swiftString(plan.pricing.annual.productId)}
        static let monthlyPackageID = ${swiftString(plan.pricing.monthly.packageId)}
        static let annualPackageID = ${swiftString(plan.pricing.annual.packageId)}
        static let featureNames = [
            ${featureNames}
        ]
    }

    enum Hosts {
        static let api = ${swiftString(endpoints.hosts.api.url)}
        static let apiHost = ${swiftString(endpoints.hosts.api.host)}
        static let marketing = ${swiftString(endpoints.hosts.marketing.url)}
        static let status = ${swiftString(endpoints.hosts.status.url)}
    }

    enum Auth {
        static let issuer = ${swiftString(endpoints.auth.issuer)}
        static let iosClientID = ${swiftString(endpoints.auth.clients.ios.id)}
        static let iosRedirectURI = ${swiftString(endpoints.auth.clients.ios.redirectUri)}
        static let callbackScheme = ${swiftString(endpoints.auth.clients.ios.scheme)}
    }
}
`;

const referencePriceLines = `        static let monthlyReferencePrice = ${swiftString(String(plan.pricing.monthly.amount))}
        static let annualReferencePrice = ${swiftString(String(plan.pricing.annual.amount))}
        static let monthlyReferenceLocalizedPrice = ${swiftString(`$${plan.pricing.monthly.amount}`)}
        static let annualReferenceLocalizedPrice = ${swiftString(`$${plan.pricing.annual.amount}`)}
`;
const generatedSwift = swift.replace(
  '        static let featureNames',
  `${referencePriceLines}        static let featureNames`,
);

const featureRows = logYourBody.features
  .map(
    (feature) =>
      `| \`${feature.id}\` | ${feature.name} | ${feature.availability} | ${feature.platforms.join(', ')} | \`${feature.entitlement}\` |`,
  )
  .join('\n');
const supportRows = logYourBody.support
  .map((option) => `| \`${option.id}\` | ${option.label} | ${option.kind} | ${option.href} |`)
  .join('\n');
const surfaceRows = logYourBody.surfaces
  .map(
    (surface) =>
      `| \`${surface.id}\` | ${surface.label} | ${surface.route} | ${surface.status} | ${surface.purpose} |`,
  )
  .join('\n');

const hostNote = (host) => ('note' in host && host.note ? host.note : '');
const hostRows = Object.entries(endpoints.hosts)
  .map(([id, host]) => `| ${id} | \`${host.url}\` | \`${host.host}\` | ${hostNote(host)} |`)
  .join('\n');

const endpointsTs = `// Generated by packages/product-registry/scripts/generate.mjs. Do not edit.
export const endpoints = ${JSON.stringify(endpoints, null, 2)} as const;
export type Endpoints = typeof endpoints;
`;

const connectSrc = [
  endpoints.hosts.api.url,
  endpoints.auth.issuer,
  `https://${endpoints.vendor.revenuecat.apiHost}`,
  `https://${endpoints.vendor.statsig.apiHost}`,
  `https://${endpoints.vendor.sentry.ingestHost}`,
  `https://${endpoints.vendor.bodyspec.authHost}`,
].join(' ');
const imgSrc = [
  "'self'",
  'data:',
  `https://${endpoints.vendor.pravatar.host}`,
  `https://${endpoints.vendor.github.avatarsHost}`,
  `https://${endpoints.vendor.cloudflare.r2PublicHost}`,
].join(' ');
const cspReportOnlyDirectives = [
  `connect-src ${connectSrc}`,
  `img-src ${imgSrc}`,
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join('; ');

const cspTs = `// Generated by packages/product-registry/scripts/generate.mjs. Do not edit.
export const cspReportOnlyDirectives = ${JSON.stringify(cspReportOnlyDirectives)};
`;

// Apple App Site Association: universal links + web credentials resolve to
// <teamId>.<bundleId>. Structure mirrors what Apple expects; keep components
// in sync with the shipped files if new sections are ever needed.
const appleAppId = `${logYourBody.identity.teamId}.${logYourBody.identity.bundleId}`;
const aasa = `${JSON.stringify(
  {
    applinks: { apps: [], details: [{ appID: appleAppId, paths: ['*'] }] },
    webcredentials: { apps: [appleAppId] },
  },
  null,
  2,
)}\n`;


const docs = [
  '<!-- Generated by packages/product-registry/scripts/generate.mjs. Do not edit. -->',
  `# ${logYourBody.identity.name} Product Registry`,
  '',
  `> ${logYourBody.brand.promise}`,
  '',
  'Canonical source: packages/product-registry/src/products/logyourbody.mjs. Web and docs import the typed package. iOS consumes the generated Swift registry.',
  '',
  '## Brand and messaging',
  '',
  `- Slogan: ${logYourBody.brand.slogan}`,
  `- Description: ${logYourBody.brand.description}`,
  `- Voice: ${logYourBody.brand.voice.join(', ')}`,
  `- Support: ${logYourBody.contacts.support}`,
  '',
  '## Plan and pricing',
  '',
  `- ${plan.name}: ${plan.entitlement}; ${plan.trialDays}-day trial; USD ${plan.pricing.monthly.amount}/month or USD ${plan.pricing.annual.amount}/year.`,
  '',
  '## Features',
  '',
  '| ID | Name | Availability | Platforms | Entitlement |',
  '|---|---|---|---|---|',
  featureRows,
  '',
  '## Support options',
  '',
  '| ID | Label | Kind | Destination |',
  '|---|---|---|---|',
  supportRows,
  '',
  '## Canonical surfaces',
  '',
  '| ID | Surface | Route | Status | Purpose |',
  '|---|---|---|---|---|',
  surfaceRows,
  '',
  '## Endpoints',
  '',
  hostRows,
  '',
  `- Auth issuer: ${endpoints.auth.issuer}`,
  `- iOS client: ${endpoints.auth.clients.ios.id}, redirect ${endpoints.auth.clients.ios.redirectUri}, scheme ${endpoints.auth.clients.ios.scheme}`,
  `- Web client: ${endpoints.auth.clients.web.id}, redirect ${endpoints.auth.clients.web.redirectUri}`,
  `- Deep links: ${endpoints.deepLinks.applinksHosts.map((host) => `applinks:${host}`).join(', ')}, scheme ${endpoints.deepLinks.scheme}`,
].join('\n');

async function sync(path, content) {
  if (check) {
    const current = await readFile(path, 'utf8').catch(() => '');
    if (current !== content) throw new Error(`${path} is stale; run pnpm product:generate`);
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
}

const prettierConfigFor = async (path) => (await resolveConfig(path)) ?? {};
const formattedDocs = await format(docs, {
  ...(await prettierConfigFor(docsPath)),
  parser: 'markdown',
});
const formattedEndpointsTs = await format(endpointsTs, {
  ...(await prettierConfigFor(endpointsTsPath)),
  parser: 'typescript',
});
const formattedCspTs = await format(cspTs, {
  ...(await prettierConfigFor(cspTsPath)),
  parser: 'typescript',
});
await Promise.all([
  sync(swiftPath, generatedSwift),
  sync(docsPath, formattedDocs),
  sync(endpointsTsPath, formattedEndpointsTs),
  sync(cspTsPath, formattedCspTs),
  sync(aasaWellKnownPath, aasa),
  sync(aasaRootPath, aasa),
]);
