import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';
import { format } from 'prettier';
import { logYourBody } from '../src/products/logyourbody.mjs';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(packageRoot, '../..');
const swiftPath = resolve(repoRoot, 'apps/ios/LogYourBody/GeneratedProductRegistry.swift');
const docsPath = resolve(repoRoot, 'docs/product/product-registry.generated.md');
const check = process.argv.includes('--check');

const swiftString = (value) => `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
const plan = logYourBody.plans[0];
const marketingFeatures = logYourBody.features.filter((feature) => feature.marketing);

const swift = `// Generated by packages/product-registry/scripts/generate.mjs. Do not edit.\nimport Foundation\n\nenum ProductRegistry {\n    static let appName = ${swiftString(logYourBody.identity.name)}\n    static let legalName = ${swiftString(logYourBody.identity.legalName)}\n    static let slogan = ${swiftString(logYourBody.brand.slogan)}\n    static let productDescription = ${swiftString(logYourBody.brand.description)}\n    static let supportEmail = ${swiftString(logYourBody.contacts.support)}\n    static let appStoreURL = ${swiftString(logYourBody.links.appStore)}\n\n    enum Contacts {\n        static let support = ${swiftString(logYourBody.contacts.support)}\n        static let privacy = ${swiftString(logYourBody.contacts.privacy)}\n        static let legal = ${swiftString(logYourBody.contacts.legal)}\n        static let careers = ${swiftString(logYourBody.contacts.careers)}\n    }\n\n    enum Paywall {\n        static let title = ${swiftString(logYourBody.messages.paywall.title)}\n        static let subtitle = ${swiftString(logYourBody.messages.paywall.subtitle)}\n        static let valueProposition = ${swiftString(logYourBody.messages.paywall.valueProposition)}\n        static let entitlementID = ${swiftString(plan.entitlement)}\n        static let trialDays = ${plan.trialDays}\n        static let monthlyProductID = ${swiftString(plan.pricing.monthly.productId)}\n        static let annualProductID = ${swiftString(plan.pricing.annual.productId)}\n        static let monthlyPackageID = ${swiftString(plan.pricing.monthly.packageId)}\n        static let annualPackageID = ${swiftString(plan.pricing.annual.packageId)}\n        static let featureNames = [${marketingFeatures.map((feature) => swiftString(feature.name)).join(', ')}]\n    }\n}\n`;

const referencePriceLines = `        static let monthlyReferencePrice = ${swiftString(String(plan.pricing.monthly.amount))}
        static let annualReferencePrice = ${swiftString(String(plan.pricing.annual.amount))}
        static let monthlyReferenceLocalizedPrice = ${swiftString(`$${plan.pricing.monthly.amount}`)}
        static let annualReferenceLocalizedPrice = ${swiftString(`$${plan.pricing.annual.amount}`)}
`;
const generatedSwift = swift.replace(
  '        static let featureNames',
  `${referencePriceLines}        static let featureNames`,
);

const featureRows = logYourBody.features
  .map(
    (feature) =>
      `| \`${feature.id}\` | ${feature.name} | ${feature.availability} | ${feature.platforms.join(', ')} | \`${feature.entitlement}\` |`,
  )
  .join('\n');
const supportRows = logYourBody.support
  .map((option) => `| \`${option.id}\` | ${option.label} | ${option.kind} | ${option.href} |`)
  .join('\n');
const surfaceRows = logYourBody.surfaces
  .map(
    (surface) =>
      `| \`${surface.id}\` | ${surface.label} | ${surface.route} | ${surface.status} | ${surface.purpose} |`,
  )
  .join('\n');

const docs = `<!-- Generated by packages/product-registry/scripts/generate.mjs. Do not edit. -->\n# ${logYourBody.identity.name} Product Registry\n\n> ${logYourBody.brand.promise}\n\nCanonical source: \`packages/product-registry/src/products/logyourbody.mjs\`. Web and docs import the typed package. iOS consumes the generated Swift registry. Run \`pnpm product:generate\` after changing product truth.\n\n## Brand and messaging\n\n- Slogan: **${logYourBody.brand.slogan}**\n- Description: ${logYourBody.brand.description}\n- Voice: ${logYourBody.brand.voice.join(', ')}\n- Support: ${logYourBody.contacts.support}\n\n## Plan and pricing\n\nThe source of live purchase price display is App Store Connect through RevenueCat. These reference prices and identifiers define web/docs copy and release drift checks.\n\n| Plan | Entitlement | Trial | Monthly | Annual |\n|---|---|---:|---:|---:|\n| ${plan.name} | \`${plan.entitlement}\` | ${plan.trialDays} days | $${plan.pricing.monthly.amount} | $${plan.pricing.annual.amount} |\n\n## Features\n\n| ID | Name | Availability | Platforms | Entitlement |\n|---|---|---|---|---|\n${featureRows}\n\n## Support options\n\n| ID | Label | Kind | Destination |\n|---|---|---|---|\n${supportRows}\n\n## Canonical surfaces\n\n| ID | Surface | Route | Status | Purpose |\n|---|---|---|---|---|\n${surfaceRows}\n`;

async function sync(path, content) {
  if (check) {
    const current = await readFile(path, 'utf8').catch(() => '');
    if (current !== content) throw new Error(`${path} is stale; run pnpm product:generate`);
    return;
  }
  await writeFile(path, content);
}

const formattedDocs = await format(docs, { parser: 'markdown' });
await Promise.all([sync(swiftPath, generatedSwift), sync(docsPath, formattedDocs)]);
