#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
IOS_DIR="${IOS_DIR:-$ROOT_DIR/apps/ios}"
APP_CONFIG_DIR="$IOS_DIR/LogYourBody"
DEV_CONFIG="$APP_CONFIG_DIR/Config-Development.xcconfig"
APP_CONFIG="$APP_CONFIG_DIR/Config.xcconfig"
SUPABASE_CONFIG="$IOS_DIR/Supabase.xcconfig"
FORCE=false

usage() {
  cat <<'USAGE'
Usage: scripts/ios/bootstrap-local-config.sh [--force]

Creates secret-free, development-only iOS config files when they are missing:
  apps/ios/LogYourBody/Config-Development.xcconfig
  apps/ios/LogYourBody/Config.xcconfig
  apps/ios/Supabase.xcconfig

Existing files are preserved unless --force is passed.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

write_if_needed() {
  local path="$1"
  local label="$2"
  local tmp

  if [[ -f "$path" && "$FORCE" != "true" ]]; then
    echo "Preserved existing $label: $path"
    return
  fi

  mkdir -p "$(dirname "$path")"
  tmp="$(mktemp "$path.XXXXXX")"
  cat > "$tmp"
  mv "$tmp" "$path"
  echo "Wrote $label: $path"
}

write_if_needed "$DEV_CONFIG" "development config" <<'CONFIG'
// Generated by scripts/ios/bootstrap-local-config.sh.
// Secret-free values for local simulator compile/UI fixture proof only.

APP_ENVIRONMENT = development
ALLOW_PRODUCTION_SERVICES_IN_DEBUG = NO

AUTH_PROVIDER_ID = custom:jovie
AUTH_REDIRECT_URI = logyourbody:/$()/oauth

SUPABASE_URL = https:/$()/local-build.supabase.co
SUPABASE_EXPECTED_HOST = local-build.supabase.co
SUPABASE_ANON_KEY = local-build-anon-key

API_BASE_URL = http:/$()/localhost:3000
API_EXPECTED_HOST = localhost

REVENUE_CAT_API_KEY =
STATSIG_CLIENT_SDK_KEY =
STATSIG_ENVIRONMENT_TIER = development
SENTRY_DSN =
SENTRY_ENVIRONMENT = development
SENTRY_TRACES_SAMPLE_RATE = 0

BODYSPEC_CLIENT_ID =
BODYSPEC_REDIRECT_URI =
CONFIG

write_if_needed "$APP_CONFIG" "active app config include" <<'CONFIG'
// Generated by scripts/ios/bootstrap-local-config.sh.
// Switch this include to Config-Production.xcconfig only for reviewed release builds.
#include "Config-Development.xcconfig"
CONFIG

write_if_needed "$SUPABASE_CONFIG" "legacy Supabase config" <<'CONFIG'
// Generated by scripts/ios/bootstrap-local-config.sh.
// Secret-free values for local simulator compile/UI fixture proof only.

SUPABASE_URL = https:/$()/local-build.supabase.co
SUPABASE_ANON_KEY = local-build-anon-key
CONFIG

echo "iOS local config bootstrap complete."
